package entity

import (
	"bytes"
	"crypto/md5"
	"fmt"
	"go/format"
	"os"
	"strings"
	"text/template"
)

const generatorVersion = "v2"

// generate produces the wiring file for an entity.
// Returns true if the file was written (changed).
func generate(ent EntityDef, pkg string, outFile string, force bool) (bool, error) {
	var buf bytes.Buffer

	data := templateData{
		Package:  pkg,
		Entity:   ent,
		HasDaos:  len(ent.Daos) > 0,
		HasComps: len(ent.Components) > 0,
		HasDirty: hasDirtyDao(ent),
	}
	data.ImportBlock = buildImportBlock(ent, data.HasDaos, data.HasComps, data.HasDirty)

	tmpl, err := template.New("entity_wire").Funcs(template.FuncMap{
		"deref":              derefType,
		"ctor":               constructorName,
		"quote":              quoteString,
		"syncTopic":          syncTopicExpr,
		"daoCollectionConst": daoCollectionConstExpr,
		"hasMethod":          hasMethod,
	}).Parse(wireTemplate)
	if err != nil {
		return false, fmt.Errorf("template parse: %w", err)
	}

	if err := tmpl.Execute(&buf, data); err != nil {
		return false, fmt.Errorf("template exec: %w", err)
	}

	content, err := format.Source(buf.Bytes())
	if err != nil {
		return false, fmt.Errorf("format generated source: %w", err)
	}

	// Check if file exists and content is unchanged
	if !force {
		existing, err := os.ReadFile(outFile)
		if err == nil {
			existingHash := fmt.Sprintf("%x", md5.Sum(existing))
			newHash := fmt.Sprintf("%x", md5.Sum(content))
			if existingHash == newHash {
				return false, nil
			}
		}
	}

	if err := os.WriteFile(outFile, content, 0644); err != nil {
		return false, err
	}

	return true, nil
}

func derefType(s string) string {
	if len(s) > 0 && s[0] == '*' {
		return s[1:]
	}
	return s
}

func constructorName(typeName string) string {
	name := derefType(typeName)
	if idx := strings.LastIndex(name, "."); idx >= 0 {
		return name[:idx+1] + "New" + name[idx+1:]
	}
	return "New" + name
}

func quoteString(s string) string {
	return fmt.Sprintf("%q", s)
}

func syncTopicExpr(s string) string {
	if s == "" {
		return `""`
	}
	if isConstExpr(s) {
		return s
	}
	return quoteString(s)
}

func daoCollectionConstExpr(typeName string) string {
	name := derefType(typeName)
	qualifier := ""
	if idx := strings.LastIndex(name, "."); idx >= 0 {
		qualifier = name[:idx+1]
		name = name[idx+1:]
	}
	return qualifier + name + "Collection"
}

func isConstExpr(s string) bool {
	if strings.ContainsAny(s, "\"'`") {
		return false
	}
	idx := strings.Index(s, ".")
	if idx <= 0 || idx == len(s)-1 {
		return false
	}
	first := s[0]
	if (first < 'A' || first > 'Z') && (first < 'a' || first > 'z') && first != '_' {
		return false
	}
	for _, r := range s[:idx] {
		if (r < 'A' || r > 'Z') && (r < 'a' || r > 'z') && (r < '0' || r > '9') && r != '_' {
			return false
		}
	}
	afterDot := s[idx+1]
	return afterDot >= 'A' && afterDot <= 'Z'
}

func hasDirtyDao(ent EntityDef) bool {
	return len(ent.Daos) > 0
}

func hasMethod(ent EntityDef, name string) bool {
	return ent.ExistingMethods != nil && ent.ExistingMethods[name]
}

func buildImportBlock(ent EntityDef, hasDaos bool, hasComps bool, hasDirty bool) string {
	var groups [][]string
	std := []string{`"sync"`}
	if hasDaos {
		std = append([]string{`"fmt"`}, std...)
	}
	groups = append(groups, std)

	local := make([]string, 0, len(ent.Imports)+2)
	for _, imp := range ent.Imports {
		if imp.Explicit {
			local = append(local, fmt.Sprintf(`%s "%s"`, imp.Alias, imp.Path))
		} else {
			local = append(local, fmt.Sprintf(`"%s"`, imp.Path))
		}
	}
	if hasDirty {
		local = append(local, `"github.com/tjbdwanghaibo/cube-core/checkpoint"`)
	}
	local = append(local, `"github.com/tjbdwanghaibo/cube-core/entity"`)
	groups = append(groups, local)

	var b strings.Builder
	for i, group := range groups {
		if i > 0 {
			b.WriteByte('\n')
		}
		for _, line := range group {
			b.WriteByte('\t')
			b.WriteString(line)
			b.WriteByte('\n')
		}
	}
	return b.String()
}

type templateData struct {
	Package     string
	Entity      EntityDef
	ImportBlock string
	HasDaos     bool
	HasComps    bool
	HasDirty    bool
}

var wireTemplate = `// Code generated by tool/entity. DO NOT EDIT.
package {{.Package}}

import (
{{.ImportBlock -}}
)

var registerEntityOnce sync.Once

// RegisterEntity registers the {{.Entity.Name}} entity builder.
func RegisterEntity() {
	registerEntityOnce.Do(func() {
		entity.RegisterEntityBuilder(&entity.EntityBuilderParam{
			Category: entity.MustEntityCategoryOfKind({{.Entity.EntityKind}}),
			Kind: {{.Entity.EntityKind}},
			Builder: func(param *entity.EntityCreateParam) (entity.IThreadSafeEntity, error) {
				return New{{.Entity.Name}}(param)
			},
{{- if .HasDaos}}
			DaoBuilders: []entity.DaoBuilderFunc{
{{- range .Entity.Daos}}
				func() entity.DaoInterface { return {{ctor .TypeName}}() },
{{- end}}
			},
{{- end}}
			NoPersist: {{.Entity.NoPersist}},
{{- if .Entity.RemotePolicy}}
			RemotePolicy: {{.Entity.RemotePolicy}},
{{- end}}
{{- if .Entity.Lifetime}}
			Lifetime: {{.Entity.Lifetime}},
{{- end}}
{{- if .Entity.Sync}}
			Sync: entity.EntitySyncBuilderParam{
				Enabled: true,
				Topic: {{syncTopic .Entity.SyncTopic}},
{{- if .Entity.SyncPacker}}
				PackerFactory: {{.Entity.SyncPacker}},
{{- end}}
			},
{{- end}}
		})
	})
}

func New{{.Entity.Name}}(param *entity.EntityCreateParam) (*{{.Entity.Name}}, error) {
	e := &{{.Entity.Name}}{}
	if err := param.NormalizeID({{.Entity.EntityKind}}); err != nil {
		return nil, err
	}

	// EntityBase
	e.EntityBase = entity.NewEntityBase(param.Id, param.Category, {{.Entity.NoPersist}}, param.Kind)
	e.EntityBase.SetHooks(e.generatedOnClear, e.generatedOnDestroy)

{{- if .HasComps}}

	// ComponentManager
	e.ComponentManager = entity.NewComponentManager()
{{- end}}
{{- if .HasDaos}}

	// DaoManager
	e.DaoManager = entity.NewDaoManager()
{{- end}}

{{- range .Entity.Daos}}

	// DAO: {{.FieldName}}
	if raw, ok := param.Dao[{{daoCollectionConst .TypeName}}]; ok {
		e.{{.FieldName}} = raw.({{.TypeName}})
	} else {
{{- if .Cold}}
		// cold DAO: initialized on demand
{{- else}}
		e.{{.FieldName}} = {{ctor .TypeName}}()
		e.{{.FieldName}}.SetId(param.StorageID())
{{- end}}
	}
	if e.{{.FieldName}} != nil {
		e.DaoManager.Set({{daoCollectionConst .TypeName}}, e.{{.FieldName}})
	}
{{- end}}

{{- range .Entity.Components}}

	// Component: {{.FieldName}}
{{- if .Cold}}
	// cold component: initialized on demand
{{- else}}
	if comp, err := entity.CreateComponent({{.CompType}}, e, param); err != nil {
		return nil, err
	} else {
		e.{{.FieldName}} = comp.({{.TypeName}})
	}
	e.ComponentManager.Set({{.CompType}}, e.{{.FieldName}})
{{- end}}
{{- end}}

{{- if .HasComps}}

	// Initialize all components in dependency order
	if err := e.ComponentManager.InitAll(param, param.IsCreate); err != nil {
		return nil, err
	}
{{- end}}

	return e, nil
}
{{- if not (hasMethod .Entity "Base")}}

func (e *{{.Entity.Name}}) Base() *entity.EntityBase { return e.EntityBase }
{{- end}}
{{- range .Entity.Components}}
{{- if and .GetterName (not (hasMethod $.Entity .GetterName))}}

func (e *{{$.Entity.Name}}) {{.GetterName}}() {{.GetterType}} { return e.{{.FieldName}} }
{{- end}}
{{- end}}
{{- range .Entity.Daos}}
{{- if and .GetterName (not (hasMethod $.Entity .GetterName))}}

func (e *{{$.Entity.Name}}) {{.GetterName}}() {{.TypeName}} { return e.{{.FieldName}} }
{{- end}}
{{- end}}

func (e *{{.Entity.Name}}) generatedOnClear() {
{{- if .HasComps}}
	e.ComponentManager.Clear()
{{- end}}
{{- if .HasDaos}}
	e.DaoManager.Clear()
{{- end}}
{{- range .Entity.Components}}
	e.{{.FieldName}} = nil
{{- end}}
{{- range .Entity.Daos}}
	e.{{.FieldName}} = nil
{{- end}}
}

func (e *{{.Entity.Name}}) generatedOnDestroy(reason entity.EntityDestroyReason) {
{{- if .HasComps}}
	e.ComponentManager.DestroyAll(reason)
{{- end}}
}
{{- if .HasDaos}}

func (e *{{.Entity.Name}}) ApplyRemoteSync(collection string, data []byte, version int64) error {
	_ = version
	switch collection {
{{- range .Entity.Daos}}
	case {{daoCollectionConst .TypeName}}:
		if e.{{.FieldName}} == nil {
			e.{{.FieldName}} = {{ctor .TypeName}}()
			e.{{.FieldName}}.SetId(e.StorageID())
			e.DaoManager.Set({{daoCollectionConst .TypeName}}, e.{{.FieldName}})
		}
		if syncDao, ok := any(e.{{.FieldName}}).(interface{ ApplySync([]byte) error }); ok {
			return syncDao.ApplySync(data)
		}
		return fmt.Errorf("{{$.Entity.Name}}: remote sync dao {{.CollName}} does not implement ApplySync")
{{- end}}
	}
	return fmt.Errorf("{{.Entity.Name}}: unknown remote sync collection %q", collection)
}

func (e *{{.Entity.Name}}) OnDataChange(data []byte, version int64) {
	payload, err := entity.DecodeRemoteSyncPayload(data)
	if err != nil {
		return
	}
	_ = e.ApplyRemoteSync(payload.Collection, payload.Data, version)
}
{{- end}}
{{- if .HasDirty}}

// Snapshot produces save items for the checkpoint system.
// Called under entity lock (guard release).
func (e *{{.Entity.Name}}) Snapshot() []checkpoint.SaveItem {
	var items []checkpoint.SaveItem
{{- range .Entity.Daos}}
	if e.{{.FieldName}} != nil {
	if mask := e.{{.FieldName}}.Tracker.TakePersistDirty(); mask != 0 {
		ver := e.{{.FieldName}}.Tracker.IncVersion()
		data := e.{{.FieldName}}.MarshalPersist(mask)
		mode := checkpoint.SaveModeFull
		var patch checkpoint.PersistPatch
		if mask != checkpoint.DirtyAll {
			if patcher, ok := any(e.{{.FieldName}}).(checkpoint.PersistPatcher); ok {
				patch = patcher.MarshalPersistPatch(mask)
				if !patch.Empty() {
					if len(patch.FullData) == 0 {
						patch.FullData = data
					}
					mode = checkpoint.SaveModePatch
				}
			}
		}
			items = append(items, checkpoint.SaveItem{
				Db:         e.{{.FieldName}}.DbName(),
				DbScope:    e.{{.FieldName}}.DbScope(),
				Collection: e.{{.FieldName}}.CollName(),
			ID:         e.{{.FieldName}}.Id(),
			Version:    ver,
			Mask:       mask,
			Mode:       mode,
			Data:       data,
			Patch:      patch,
			Tracker:    &e.{{.FieldName}}.Tracker,
		})
	}
	}
{{- end}}
	return items
}
{{- end}}
`
