package attribute

import (
	"bytes"
	"fmt"
	"strings"
)

func generate(profile ProfileDef) ([]byte, error) {
	var b bytes.Buffer
	recv := strings.ToLower(profile.Name[:1])
	lower := lowerFirst(profile.Name)

	fmt.Fprintf(&b, "// Code generated by tool/attribute. DO NOT EDIT.\n")
	fmt.Fprintf(&b, "package %s\n\n", profile.Package)

	fmt.Fprintf(&b, "const (\n")
	fmt.Fprintf(&b, "\tAttr%sBegin AttrID = %d\n", profile.Name, profile.IndexBegin)
	fmt.Fprintf(&b, "\tAttr%sMaxCount = %d\n", profile.Name, profile.MaxCount)
	for _, field := range profile.Fields {
		fmt.Fprintf(&b, "\t%s AttrID = %d\n", field.ConstName, field.ID)
	}
	fmt.Fprintf(&b, ")\n\n")

	fmt.Fprintf(&b, "const (\n")
	for _, field := range profile.Fields {
		fmt.Fprintf(&b, "\t%s uint64 = 1 << %d\n", field.MaskName, field.Bit)
	}
	fmt.Fprintf(&b, ")\n\n")

	fmt.Fprintf(&b, "var %sMetaByID = map[AttrID]AttributeMeta{\n", lower)
	for _, field := range profile.Fields {
		fmt.Fprintf(&b, "\t%s: {ID: %s, Name: %q, Field: %q, Mask: %s, Derived: %t},\n", field.ConstName, field.ConstName, field.AttrName, field.Name, field.MaskName, field.Derived)
	}
	fmt.Fprintf(&b, "}\n\n")

	fmt.Fprintf(&b, "var %sMetaByName = map[string]AttributeMeta{\n", lower)
	for _, field := range profile.Fields {
		fmt.Fprintf(&b, "\t%q: %sMetaByID[%s],\n", field.AttrName, lower, field.ConstName)
		fmt.Fprintf(&b, "\t%q: %sMetaByID[%s],\n", field.Name, lower, field.ConstName)
	}
	fmt.Fprintf(&b, "}\n\n")

	fmt.Fprintf(&b, "func New%sProfile() AttributeProfile { return &%s{} }\n\n", profile.Name, profile.Name)

	fmt.Fprintf(&b, "func (%s *%s) Reset() {\n", recv, profile.Name)
	fmt.Fprintf(&b, "\tif %s == nil { return }\n", recv)
	fmt.Fprintf(&b, "\t*%s = %s{}\n", recv, profile.Name)
	fmt.Fprintf(&b, "}\n\n")

	fmt.Fprintf(&b, "func (%s *%s) CloneProfile() AttributeProfile {\n", recv, profile.Name)
	fmt.Fprintf(&b, "\tif %s == nil { return nil }\n", recv)
	fmt.Fprintf(&b, "\tcp := *%s\n", recv)
	fmt.Fprintf(&b, "\treturn &cp\n")
	fmt.Fprintf(&b, "}\n\n")

	fmt.Fprintf(&b, "func (%s *%s) DirtyMask() uint64 {\n", recv, profile.Name)
	fmt.Fprintf(&b, "\tif %s == nil { return 0 }\n", recv)
	fmt.Fprintf(&b, "\treturn %s.dirtyMask\n", recv)
	fmt.Fprintf(&b, "}\n\n")

	fmt.Fprintf(&b, "func (%s *%s) ClearDirty() {\n", recv, profile.Name)
	fmt.Fprintf(&b, "\tif %s != nil { %s.dirtyMask = 0 }\n", recv, recv)
	fmt.Fprintf(&b, "}\n\n")

	fmt.Fprintf(&b, "func (%s *%s) markAttrDirty(mask uint64) { %s.dirtyMask |= mask }\n\n", recv, profile.Name, recv)

	for _, field := range profile.Fields {
		fmt.Fprintf(&b, "func (%s *%s) Set%s(value %s) bool {\n", recv, profile.Name, field.Name, field.Type)
		fmt.Fprintf(&b, "\tif %s == nil || %s.%s == value { return false }\n", recv, recv, field.Name)
		fmt.Fprintf(&b, "\t%s.%s = value\n", recv, field.Name)
		fmt.Fprintf(&b, "\t%s.markAttrDirty(%s)\n", recv, field.MaskName)
		fmt.Fprintf(&b, "\treturn true\n")
		fmt.Fprintf(&b, "}\n\n")
	}

	fmt.Fprintf(&b, "func (%s *%s) SetAttr(id AttrID, value AttrValue) bool {\n", recv, profile.Name)
	fmt.Fprintf(&b, "\tif %s == nil { return false }\n", recv)
	fmt.Fprintf(&b, "\tswitch id {\n")
	for _, field := range profile.Fields {
		fmt.Fprintf(&b, "\tcase %s:\n\t\treturn %s.Set%s(%s(value))\n", field.ConstName, recv, field.Name, field.Type)
	}
	fmt.Fprintf(&b, "\tdefault:\n\t\treturn false\n\t}\n")
	fmt.Fprintf(&b, "}\n\n")

	fmt.Fprintf(&b, "func (%s *%s) SetDirectAttr(id AttrID, value AttrValue) bool {\n", recv, profile.Name)
	fmt.Fprintf(&b, "\tif %s == nil { return false }\n", recv)
	fmt.Fprintf(&b, "\tswitch id {\n")
	for _, field := range profile.Fields {
		if field.Derived {
			continue
		}
		fmt.Fprintf(&b, "\tcase %s:\n\t\treturn %s.Set%s(%s(value))\n", field.ConstName, recv, field.Name, field.Type)
	}
	fmt.Fprintf(&b, "\tdefault:\n\t\treturn false\n\t}\n")
	fmt.Fprintf(&b, "}\n\n")

	fmt.Fprintf(&b, "func (%s *%s) GetAttr(id AttrID) (AttrValue, bool) {\n", recv, profile.Name)
	fmt.Fprintf(&b, "\tif %s == nil { return 0, false }\n", recv)
	fmt.Fprintf(&b, "\tswitch id {\n")
	for _, field := range profile.Fields {
		fmt.Fprintf(&b, "\tcase %s:\n\t\treturn AttrValue(%s.%s), true\n", field.ConstName, recv, field.Name)
	}
	fmt.Fprintf(&b, "\tdefault:\n\t\treturn 0, false\n\t}\n")
	fmt.Fprintf(&b, "}\n\n")

	fmt.Fprintf(&b, "func (%s *%s) LoadValues(values map[AttrID]AttrValue) uint64 {\n", recv, profile.Name)
	fmt.Fprintf(&b, "\tif %s == nil { return 0 }\n", recv)
	fmt.Fprintf(&b, "\tbefore := %s.dirtyMask\n", recv)
	fmt.Fprintf(&b, "\tfor id, value := range values { %s.SetDirectAttr(id, value) }\n", recv)
	fmt.Fprintf(&b, "\t%s.Update()\n", recv)
	fmt.Fprintf(&b, "\treturn %s.dirtyMask &^ before\n", recv)
	fmt.Fprintf(&b, "}\n\n")

	fmt.Fprintf(&b, "func (%s *%s) ExportValues(dst map[AttrID]AttrValue) {\n", recv, profile.Name)
	fmt.Fprintf(&b, "\tif %s == nil || dst == nil { return }\n", recv)
	for _, field := range profile.Fields {
		fmt.Fprintf(&b, "\tif %s.%s != 0 { dst[%s] = AttrValue(%s.%s) } else { delete(dst, %s) }\n", recv, field.Name, field.ConstName, recv, field.Name, field.ConstName)
	}
	fmt.Fprintf(&b, "}\n\n")

	for _, formula := range profile.Formulas {
		output := profile.Fields[formula.Output]
		fmt.Fprintf(&b, "func (%s *%s) recompute%s() bool {\n", recv, profile.Name, output.Name)
		fmt.Fprintf(&b, "\tnext := %s.%s(", recv, formula.Method)
		for i, inputIdx := range formula.Inputs {
			if i > 0 {
				fmt.Fprintf(&b, ", ")
			}
			fmt.Fprintf(&b, "%s.%s", recv, profile.Fields[inputIdx].Name)
		}
		fmt.Fprintf(&b, ")\n")
		fmt.Fprintf(&b, "\tif %s.%s == next { return false }\n", recv, output.Name)
		fmt.Fprintf(&b, "\t%s.%s = next\n", recv, output.Name)
		fmt.Fprintf(&b, "\t%s.markAttrDirty(%s)\n", recv, output.MaskName)
		fmt.Fprintf(&b, "\treturn true\n")
		fmt.Fprintf(&b, "}\n\n")
	}

	fmt.Fprintf(&b, "func (%s *%s) Update() bool {\n", recv, profile.Name)
	fmt.Fprintf(&b, "\tif %s == nil { return false }\n", recv)
	fmt.Fprintf(&b, "\tchanged := false\n")
	for _, formula := range profile.Formulas {
		output := profile.Fields[formula.Output]
		fmt.Fprintf(&b, "\tif %s.dirtyMask&(", recv)
		for i, inputIdx := range formula.Inputs {
			if i > 0 {
				fmt.Fprintf(&b, "|")
			}
			fmt.Fprintf(&b, "%s", profile.Fields[inputIdx].MaskName)
		}
		fmt.Fprintf(&b, ") != 0 {\n")
		fmt.Fprintf(&b, "\t\tif %s.recompute%s() { changed = true }\n", recv, output.Name)
		fmt.Fprintf(&b, "\t}\n")
	}
	fmt.Fprintf(&b, "\treturn changed\n")
	fmt.Fprintf(&b, "}\n\n")

	fmt.Fprintf(&b, "func (%s *%s) MetaByID(id AttrID) (AttributeMeta, bool) {\n", recv, profile.Name)
	fmt.Fprintf(&b, "\tmeta, ok := %sMetaByID[id]\n", lower)
	fmt.Fprintf(&b, "\treturn meta, ok\n")
	fmt.Fprintf(&b, "}\n\n")

	fmt.Fprintf(&b, "func (%s *%s) MetaByName(name string) (AttributeMeta, bool) {\n", recv, profile.Name)
	fmt.Fprintf(&b, "\tmeta, ok := %sMetaByName[name]\n", lower)
	fmt.Fprintf(&b, "\treturn meta, ok\n")
	fmt.Fprintf(&b, "}\n\n")

	fmt.Fprintf(&b, "func (s Snapshot) %s() (*%s, bool) {\n", profile.Name, profile.Name)
	fmt.Fprintf(&b, "\tif s.Profile == nil { return nil, false }\n")
	fmt.Fprintf(&b, "\tp, ok := s.Profile.(*%s)\n", profile.Name)
	fmt.Fprintf(&b, "\tif !ok || p == nil { return nil, false }\n")
	fmt.Fprintf(&b, "\tcp := *p\n")
	fmt.Fprintf(&b, "\treturn &cp, true\n")
	fmt.Fprintf(&b, "}\n\n")

	fmt.Fprintf(&b, "func (c *Container) %s(selector Selector) (*%s, bool) {\n", profile.Name, profile.Name)
	fmt.Fprintf(&b, "\tif c == nil { return nil, false }\n")
	fmt.Fprintf(&b, "\treturn c.Snapshot(selector).%s()\n", profile.Name)
	fmt.Fprintf(&b, "}\n")

	return formatGo(b.Bytes())
}
