package dao

var nestedTemplate = `// Code generated by tool/dao. DO NOT EDIT.
package {{.Package}}

import (
	"github.com/tjbdwanghaibo/cube-core/checkpoint"
	"github.com/tjbdwanghaibo/cube-core/nest"
{{- if hasMaps .Nested.Fields}}
	fmap "github.com/tjbdwanghaibo/cube-core/map"
{{- end}}
)

// {{.Nested.Name}} is a nested struct with dirty propagation.
type {{.Nested.Name}} struct {
	checkpoint.DirtyHook
{{- range .Nested.Fields}}
	{{.Name}} {{fieldType .}}
{{- end}}
}
{{range $idx, $field := .Nested.Fields}}
func (s *{{$.Nested.Name}}) Set{{.Name}}(v {{if eq .Kind 2}}{{rawMapType .}}{{else}}{{.TypeStr}}{{end}}) {
	if tx := nest.CurrentRollbackTx(); tx != nil && tx.Policy() == nest.RollbackUndo {
		old := s.{{.Name}}
		_ = tx.RecordUndo(s, uint64({{$idx}}), func() error { s.{{.Name}} = old; return nil })
	}
{{- if eq .Kind 0}}
	if s.{{.Name}} != v {
		s.{{.Name}} = v
		s.Mark()
	}
{{- else if eq .Kind 2}}
	s.{{.Name}} = {{mapNewExpr . "len(v)"}}
	for key, val := range v {
		s.{{.Name}}.Set(key, val)
	}
	s.Mark()
{{- else}}
	s.{{.Name}} = v
	s.Mark()
{{- end}}
}
{{end}}`
