package dao

var daoTemplate = `// Code generated by tool/dao. DO NOT EDIT.
package {{.Package}}

import (
	"github.com/tjbdwanghaibo/cube-core/checkpoint"
	"github.com/tjbdwanghaibo/cube-core/entity"
	"github.com/tjbdwanghaibo/cube-core/migration"
{{- if .HasMaps}}
	fmap "github.com/tjbdwanghaibo/cube-core/map"
{{- end}}
	"go.mongodb.org/mongo-driver/bson"
)

// {{.Dao.Name}} is the DAO for collection "{{.Dao.Coll}}".
type {{.Dao.Name}} struct {
	id      int64
	Tracker checkpoint.DirtyTracker
	persistPatchSet map[string]any
	persistPatchUnset []string
	persistPatchFull map[string]bool
{{- range .Dao.Fields}}
	{{.Name}} {{fieldType .}}
{{- end}}
}

// Ensure interface compliance.
var _ entity.DaoInterface = (*{{.Dao.Name}})(nil)

const (
	{{daoDBConst .Dao.Name}} = "{{.Dao.Db}}"
	{{daoCollConst .Dao.Name}} = "{{.Dao.Coll}}"
	{{.Dao.Name}}SchemaVersion uint32 = 1
)

// New{{.Dao.Name}} creates a new {{.Dao.Name}} instance with initialized maps/slices.
func New{{.Dao.Name}}() *{{.Dao.Name}} {
	d := &{{.Dao.Name}}{}
{{- range .Dao.Fields}}
{{- if eq .Kind 2}}
	d.{{.Name}} = {{mapNewExpr . "0"}}
{{- end}}
{{- end}}
	return d
}

func (d *{{.Dao.Name}}) Id() int64        { return d.id }
func (d *{{.Dao.Name}}) SetId(id int64)   { d.id = id }
func (d *{{.Dao.Name}}) DbName() string   { return {{daoDBConst .Dao.Name}} }
func (d *{{.Dao.Name}}) CollName() string  { return {{daoCollConst .Dao.Name}} }
func (d *{{.Dao.Name}}) SchemaVersion() uint32 { return {{.Dao.Name}}SchemaVersion }
func (d *{{.Dao.Name}}) Migrate(raw []byte, from uint32) ([]byte, error) { return migration.MigrateDAO(d.CollName(), raw, from, {{.Dao.Name}}SchemaVersion) }
func (d *{{.Dao.Name}}) Dirty() entity.IDirty { return &d.Tracker }
func (d *{{.Dao.Name}}) CleanDirty()      { d.Tracker.SelfClean(); d.clearPersistPathPatch() }
func (d *{{.Dao.Name}}) DirtyTracker() *checkpoint.DirtyTracker { return &d.Tracker }

const (
{{- range .Dao.Fields}}
	{{fieldMaskName $.Dao.Name .Name}} uint64 = 1 << iota
{{- end}}
)

{{range .Dao.Fields}}
func (d *{{$.Dao.Name}}) mark{{.Name}}Dirty() {
	d.Tracker.MarkScope({{dirtyScope .}}, {{fieldMaskName $.Dao.Name .Name}})
}
{{end}}

func (d *{{.Dao.Name}}) recordPersistPatchSet(field string, path string, value any) {
	if path == "" {
		d.recordPersistPatchFull(field)
		return
	}
	if d.persistPatchSet == nil {
		d.persistPatchSet = make(map[string]any)
	}
	d.persistPatchSet[path] = value
	for i := 0; i < len(d.persistPatchUnset); {
		if d.persistPatchUnset[i] == path {
			d.persistPatchUnset = append(d.persistPatchUnset[:i], d.persistPatchUnset[i+1:]...)
			continue
		}
		i++
	}
}

func (d *{{.Dao.Name}}) recordPersistPatchUnset(field string, path string) {
	if path == "" {
		d.recordPersistPatchFull(field)
		return
	}
	delete(d.persistPatchSet, path)
	d.persistPatchUnset = append(d.persistPatchUnset, path)
}

func (d *{{.Dao.Name}}) recordPersistPatchFull(field string) {
	if field == "" {
		return
	}
	if d.persistPatchFull == nil {
		d.persistPatchFull = make(map[string]bool)
	}
	d.persistPatchFull[field] = true
}

func (d *{{.Dao.Name}}) hasPersistPathPatch(field string) bool {
	return checkpoint.PersistPatchHasPath(d.persistPatchSet, d.persistPatchUnset, field)
}

func (d *{{.Dao.Name}}) appendPersistPathPatch(patch *checkpoint.PersistPatch, fullFields map[string]bool) {
	for path, value := range d.persistPatchSet {
		if checkpoint.PersistPatchPathCovered(path, fullFields) {
			continue
		}
		patch.Set[path] = value
	}
	for _, path := range d.persistPatchUnset {
		if checkpoint.PersistPatchPathCovered(path, fullFields) {
			continue
		}
		patch.Unset = append(patch.Unset, path)
	}
	d.clearPersistPathPatch()
}

func (d *{{.Dao.Name}}) clearPersistPathPatch() {
	d.persistPatchSet = nil
	d.persistPatchUnset = nil
	d.persistPatchFull = nil
}

{{range .Dao.Fields}}
{{- if eq .Kind 2}}
func (d *{{$.Dao.Name}}) mark{{.Name}}KeyDirty(key {{.MapKey}}, val {{mapValType .}}) {
	if path, ok := checkpoint.MapPatchPath("{{bsonKey .Name}}", key); ok {
		d.recordPersistPatchSet("{{bsonKey .Name}}", path, val)
	} else {
		d.recordPersistPatchFull("{{bsonKey .Name}}")
	}
	d.mark{{.Name}}Dirty()
}

func (d *{{$.Dao.Name}}) mark{{.Name}}KeyDeleted(key {{.MapKey}}) {
	if path, ok := checkpoint.MapPatchPath("{{bsonKey .Name}}", key); ok {
		d.recordPersistPatchUnset("{{bsonKey .Name}}", path)
	} else {
		d.recordPersistPatchFull("{{bsonKey .Name}}")
	}
	d.mark{{.Name}}Dirty()
}
{{end}}
{{- end}}

// Init wires dirty callbacks for nested structs and map values.
func (d *{{.Dao.Name}}) Init() {
{{- range .Dao.Fields}}
{{- if eq .Kind 3}}
{{- if isNested .TypeStr}}
	d.{{.Name}}.SetNotify(d.mark{{.Name}}Dirty)
{{- end}}
{{- end}}
{{- if eq .Kind 2}}
{{- if .IsPtr}}
{{- if isNested .MapVal}}
	if d.{{.Name}} != nil {
		d.{{.Name}}.Range(func(key {{.MapKey}}, v {{mapValType .}}) bool {
			if v != nil {
				key, v := key, v
				v.SetNotify(func() { d.mark{{.Name}}KeyDirty(key, v) })
			}
			return true
		})
	}
{{- end}}
{{- end}}
{{- end}}
{{- if eq .Kind 1}}
{{- if .IsPtr}}
{{- if isNested .SliceElem}}
	for _, v := range d.{{.Name}} {
		v.SetNotify(d.mark{{.Name}}Dirty)
	}
{{- end}}
{{- end}}
{{- end}}
{{- end}}
}

// --- Setters ---
{{range dirtyFields .Dao.Fields}}
{{- if eq .Kind 0}}
func (d *{{$.Dao.Name}}) Set{{.Name}}(v {{.TypeStr}}) {
	if d.{{.Name}} != v {
		d.{{.Name}} = v
		d.mark{{.Name}}Dirty()
	}
}
{{end}}
{{- if eq .Kind 3}}
func (d *{{$.Dao.Name}}) Set{{.Name}}(v {{.TypeStr}}) {
	d.{{.Name}} = v
{{- if isNested .TypeStr}}
	d.{{.Name}}.SetNotify(d.mark{{.Name}}Dirty)
{{- end}}
	d.mark{{.Name}}Dirty()
}
{{end}}
{{- if eq .Kind 2}}
func (d *{{$.Dao.Name}}) Get{{.Name}}(key {{.MapKey}}) ({{if .IsPtr}}*{{.MapVal}}{{else}}{{.MapVal}}{{end}}, bool) {
	if d.{{.Name}} == nil {
		var zero {{mapValType .}}
		return zero, false
	}
	return d.{{.Name}}.Get(key)
}

func (d *{{$.Dao.Name}}) Set{{.Name}}(key {{.MapKey}}, val {{if .IsPtr}}*{{.MapVal}}{{else}}{{.MapVal}}{{end}}) {
	if d.{{.Name}} == nil {
		d.{{.Name}} = {{mapNewExpr . "0"}}
	}
{{- if .IsPtr}}
{{- if isNested .MapVal}}
	if val != nil {
		val.SetNotify(func() { d.mark{{.Name}}KeyDirty(key, val) })
	}
{{- end}}
{{- end}}
	d.{{.Name}}.Set(key, val)
	d.mark{{.Name}}KeyDirty(key, val)
}

func (d *{{$.Dao.Name}}) Del{{.Name}}(key {{.MapKey}}) {
	if d.{{.Name}} == nil {
		return
	}
{{- if .IsPtr}}
{{- if isNested .MapVal}}
	if v, ok := d.{{.Name}}.Get(key); ok && v != nil {
		v.SetNotify(nil)
	}
{{- end}}
{{- end}}
	if d.{{.Name}}.Delete(key) {
		d.mark{{.Name}}KeyDeleted(key)
	}
}

func (d *{{$.Dao.Name}}) Range{{.Name}}(f func(key {{.MapKey}}, val {{if .IsPtr}}*{{.MapVal}}{{else}}{{.MapVal}}{{end}}) bool) {
	if d.{{.Name}} == nil || f == nil {
		return
	}
	d.{{.Name}}.Range(f)
}

func (d *{{$.Dao.Name}}) {{.Name}}Len() int {
	if d.{{.Name}} == nil {
		return 0
	}
	return d.{{.Name}}.Len()
}
{{end}}
{{- if eq .Kind 1}}
func (d *{{$.Dao.Name}}) Add{{.Name}}(v {{if .IsPtr}}*{{.SliceElem}}{{else}}{{.SliceElem}}{{end}}) {
{{- if .IsPtr}}
{{- if isNested .SliceElem}}
	v.SetNotify(d.mark{{.Name}}Dirty)
{{- end}}
{{- end}}
	d.{{.Name}} = append(d.{{.Name}}, v)
	d.mark{{.Name}}Dirty()
}

func (d *{{$.Dao.Name}}) Set{{.Name}}All(v {{.TypeStr}}) {
{{- if .IsPtr}}
{{- if isNested .SliceElem}}
	for _, item := range v {
		item.SetNotify(d.mark{{.Name}}Dirty)
	}
{{- end}}
{{- end}}
	d.{{.Name}} = v
	d.mark{{.Name}}Dirty()
}

func (d *{{$.Dao.Name}}) Range{{.Name}}(f func(idx int, val {{if .IsPtr}}*{{.SliceElem}}{{else}}{{.SliceElem}}{{end}}) bool) {
	for i, v := range d.{{.Name}} {
		if !f(i, v) {
			break
		}
	}
}

func (d *{{$.Dao.Name}}) {{.Name}}Len() int {
	return len(d.{{.Name}})
}
{{end}}
{{- end}}

{{range .Dao.Fields}}
{{- if eq .Kind 2}}
func (d *{{$.Dao.Name}}) {{mapHelperName $.Dao.Name .Name}}() {{rawMapType .}} {
	if d.{{.Name}} == nil {
		return nil
	}
	ret := make({{rawMapType .}}, d.{{.Name}}.Len())
	d.{{.Name}}.Range(func(key {{.MapKey}}, val {{mapValType .}}) bool {
		ret[key] = val
		return true
	})
	return ret
}

func (d *{{$.Dao.Name}}) set{{.Name}}RawMap(src {{rawMapType .}}) {
	d.{{.Name}} = {{mapNewExpr . "len(src)"}}
	for key, val := range src {
{{- if .IsPtr}}
{{- if isNested .MapVal}}
		if val != nil {
			key, val := key, val
			val.SetNotify(func() { d.mark{{.Name}}KeyDirty(key, val) })
		}
{{- end}}
{{- end}}
		d.{{.Name}}.Set(key, val)
	}
}
{{end}}
{{- end}}

// --- Marshal (persist fields) ---

func (d *{{.Dao.Name}}) Marshal() []byte {
	return d.MarshalPersist(checkpoint.DirtyAll)
}

func (d *{{.Dao.Name}}) MarshalPersist(mask uint64) []byte {
	data := d.marshalPersistData(mask)
	if mask == checkpoint.DirtyAll {
		d.clearPersistPathPatch()
	}
	return data
}

func (d *{{.Dao.Name}}) marshalPersistData(mask uint64) []byte {
	_ = mask // full payload is used for inserts and safe fallback.
	doc := bson.M{
		"_id": d.id,
		"_schema": {{.Dao.Name}}SchemaVersion,
{{- range persistFields .Dao.Fields}}
{{- if eq .Kind 2}}
		"{{bsonKey .Name}}": d.{{mapHelperName $.Dao.Name .Name}}(),
{{- else}}
		"{{bsonKey .Name}}": d.{{.Name}},
{{- end}}
{{- end}}
	}
	data, _ := bson.Marshal(doc)
	return data
}

func (d *{{.Dao.Name}}) MarshalPersistPatch(mask uint64) checkpoint.PersistPatch {
	patch := checkpoint.PersistPatch{
		Set:      make(map[string]any),
		FullData: d.marshalPersistData(checkpoint.DirtyAll),
	}
	if mask == 0 || mask == checkpoint.DirtyAll {
		d.clearPersistPathPatch()
		return patch
	}
	fullFields := make(map[string]bool)
{{- range persistFields .Dao.Fields}}
	if mask&{{fieldMaskName $.Dao.Name .Name}} != 0 {
{{- if eq .Kind 2}}
		if d.persistPatchFull["{{bsonKey .Name}}"] || !d.hasPersistPathPatch("{{bsonKey .Name}}") {
			patch.Set["{{bsonKey .Name}}"] = d.{{mapHelperName $.Dao.Name .Name}}()
			fullFields["{{bsonKey .Name}}"] = true
		}
{{- else}}
		patch.Set["{{bsonKey .Name}}"] = d.{{.Name}}
{{- end}}
	}
{{- end}}
	d.appendPersistPathPatch(&patch, fullFields)
	if len(patch.Set) == 0 {
		patch.Set = nil
	}
	return patch
}

func (d *{{.Dao.Name}}) MarshalSync(mask uint64) []byte {
	doc := bson.M{
		"_id": d.id,
	}
{{- range syncFields .Dao.Fields}}
	if mask&{{fieldMaskName $.Dao.Name .Name}} != 0 {
{{- if eq .Kind 2}}
		doc["{{bsonKey .Name}}"] = d.{{mapHelperName $.Dao.Name .Name}}()
{{- else}}
		doc["{{bsonKey .Name}}"] = d.{{.Name}}
{{- end}}
	}
{{- end}}
	if len(doc) == 1 {
		return nil
	}
	data, _ := bson.Marshal(doc)
	return data
}

func (d *{{.Dao.Name}}) ApplySync(raw []byte) error {
	var doc bson.M
	if err := bson.Unmarshal(raw, &doc); err != nil {
		return err
	}
{{- range syncFields .Dao.Fields}}
	if v, ok := doc["{{bsonKey .Name}}"]; ok {
		data, err := bson.Marshal(bson.M{"v": v})
		if err != nil {
			return err
		}
		var wrap struct {
			V {{if eq .Kind 2}}{{rawMapType .}}{{else}}{{.TypeStr}}{{end}} ` + "`" + `bson:"v"` + "`" + `
		}
		if err := bson.Unmarshal(data, &wrap); err != nil {
			return err
		}
{{- if eq .Kind 2}}
		d.set{{.Name}}RawMap(wrap.V)
{{- else}}
		d.{{.Name}} = wrap.V
{{- end}}
	}
{{- end}}
	d.Init()
	return nil
}

// --- Unmarshal ---

func (d *{{.Dao.Name}}) Unmarshal(raw []byte) error {
	type rawDoc struct {
		Id int64 ` + "`" + `bson:"_id"` + "`" + `
{{- range persistFields .Dao.Fields}}
		{{.Name}} {{if eq .Kind 2}}{{rawMapType .}}{{else}}{{.TypeStr}}{{end}} ` + "`" + `bson:"{{bsonKey .Name}}"` + "`" + `
{{- end}}
	}
	var dd rawDoc
	if err := bson.Unmarshal(raw, &dd); err != nil {
		return err
	}
	d.id = dd.Id
{{- range persistFields .Dao.Fields}}
{{- if eq .Kind 2}}
	d.set{{.Name}}RawMap(dd.{{.Name}})
{{- else}}
	d.{{.Name}} = dd.{{.Name}}
{{- end}}
{{- end}}
	d.Init()
	return nil
}

// compile-time import guards
var (
	_ = checkpoint.DirtyTracker{}
	_ = bson.M{}
)
`
