// Code generated by tool/dao. DO NOT EDIT.
package testdata

import (
	"github.com/tjbdwanghaibo/cube-core/checkpoint"
)

// GemInfo is a nested struct with dirty propagation.
type GemInfo struct {
	checkpoint.DirtyHook
	ID    int32
	Level int32
}

func (s *GemInfo) SetID(v int32) {
	if s.ID != v {
		s.ID = v
		s.Mark()
	}
}

func (s *GemInfo) SetLevel(v int32) {
	if s.Level != v {
		s.Level = v
		s.Mark()
	}
}
