// Code generated by tool/dao. DO NOT EDIT.
package testdata

import (
	"github.com/tjbdwanghaibo/cube-core/checkpoint"
	fmap "github.com/tjbdwanghaibo/cube-core/map"
)

// EquipInfo is a nested struct with dirty propagation.
type EquipInfo struct {
	checkpoint.DirtyHook
	Level int32
	Star  int32
	Gems  *fmap.SmallSafeMap[int32, *GemInfo]
}

func (s *EquipInfo) SetLevel(v int32) {
	if s.Level != v {
		s.Level = v
		s.Mark()
	}
}

func (s *EquipInfo) SetStar(v int32) {
	if s.Star != v {
		s.Star = v
		s.Mark()
	}
}

func (s *EquipInfo) SetGems(v map[int32]*GemInfo) {
	s.Gems = fmap.NewSmallSafeMap[int32, *GemInfo](len(v))
	for key, val := range v {
		s.Gems.Set(key, val)
	}
	s.Mark()
}
