// Code generated by tool/dao. DO NOT EDIT.
package testdata

import (
	"github.com/tjbdwanghaibo/cube-core/checkpoint"
	"github.com/tjbdwanghaibo/cube-core/entity"
	fmap "github.com/tjbdwanghaibo/cube-core/map"
	"github.com/tjbdwanghaibo/cube-core/migration"
	"go.mongodb.org/mongo-driver/bson"
)

// HeroDao is the DAO for collection "heroes".
type HeroDao struct {
	id                int64
	Tracker           checkpoint.DirtyTracker
	persistPatchSet   map[string]any
	persistPatchUnset []string
	persistPatchFull  map[string]bool
	Name              string
	Level             int32
	Exp               int64
	LoginAt           int64
	Items             *fmap.SmallSafeMap[int64, int32]
	Friends           []int64
	Pos               Position
	Equips            *fmap.SmallSafeMap[int64, *EquipInfo]
}

// Ensure interface compliance.
var _ entity.DaoInterface = (*HeroDao)(nil)

const (
	HeroDaoDBName               = "game"
	HeroDaoCollection           = "heroes"
	HeroDaoSchemaVersion uint32 = 1
)

// NewHeroDao creates a new HeroDao instance with initialized maps/slices.
func NewHeroDao() *HeroDao {
	d := &HeroDao{}
	d.Items = fmap.NewSmallSafeMap[int64, int32](0)
	d.Equips = fmap.NewSmallSafeMap[int64, *EquipInfo](0)
	return d
}

func (d *HeroDao) Id() int64             { return d.id }
func (d *HeroDao) SetId(id int64)        { d.id = id }
func (d *HeroDao) DbName() string        { return HeroDaoDBName }
func (d *HeroDao) CollName() string      { return HeroDaoCollection }
func (d *HeroDao) SchemaVersion() uint32 { return HeroDaoSchemaVersion }
func (d *HeroDao) Migrate(raw []byte, from uint32) ([]byte, error) {
	return migration.MigrateDAO(d.CollName(), raw, from, HeroDaoSchemaVersion)
}
func (d *HeroDao) Dirty() entity.IDirty                   { return &d.Tracker }
func (d *HeroDao) CleanDirty()                            { d.Tracker.SelfClean(); d.clearPersistPathPatch() }
func (d *HeroDao) DirtyTracker() *checkpoint.DirtyTracker { return &d.Tracker }

const (
	heroDaoFieldName    uint64 = 1 << iota
	heroDaoFieldLevel   uint64 = 1 << iota
	heroDaoFieldExp     uint64 = 1 << iota
	heroDaoFieldLoginAt uint64 = 1 << iota
	heroDaoFieldItems   uint64 = 1 << iota
	heroDaoFieldFriends uint64 = 1 << iota
	heroDaoFieldPos     uint64 = 1 << iota
	heroDaoFieldEquips  uint64 = 1 << iota
)

func (d *HeroDao) markNameDirty() {
	d.Tracker.MarkScope(checkpoint.DirtyPersist|checkpoint.DirtySync, heroDaoFieldName)
}

func (d *HeroDao) markLevelDirty() {
	d.Tracker.MarkScope(checkpoint.DirtyPersist|checkpoint.DirtySync, heroDaoFieldLevel)
}

func (d *HeroDao) markExpDirty() {
	d.Tracker.MarkScope(checkpoint.DirtyPersist|checkpoint.DirtySync, heroDaoFieldExp)
}

func (d *HeroDao) markLoginAtDirty() {
	d.Tracker.MarkScope(checkpoint.DirtyPersist, heroDaoFieldLoginAt)
}

func (d *HeroDao) markItemsDirty() {
	d.Tracker.MarkScope(checkpoint.DirtyPersist|checkpoint.DirtySync, heroDaoFieldItems)
}

func (d *HeroDao) markFriendsDirty() {
	d.Tracker.MarkScope(checkpoint.DirtyPersist|checkpoint.DirtySync, heroDaoFieldFriends)
}

func (d *HeroDao) markPosDirty() {
	d.Tracker.MarkScope(checkpoint.DirtyPersist|checkpoint.DirtySync, heroDaoFieldPos)
}

func (d *HeroDao) markEquipsDirty() {
	d.Tracker.MarkScope(checkpoint.DirtyPersist|checkpoint.DirtySync, heroDaoFieldEquips)
}

func (d *HeroDao) recordPersistPatchSet(field string, path string, value any) {
	if path == "" {
		d.recordPersistPatchFull(field)
		return
	}
	if d.persistPatchSet == nil {
		d.persistPatchSet = make(map[string]any)
	}
	d.persistPatchSet[path] = value
	for i := 0; i < len(d.persistPatchUnset); {
		if d.persistPatchUnset[i] == path {
			d.persistPatchUnset = append(d.persistPatchUnset[:i], d.persistPatchUnset[i+1:]...)
			continue
		}
		i++
	}
}

func (d *HeroDao) recordPersistPatchUnset(field string, path string) {
	if path == "" {
		d.recordPersistPatchFull(field)
		return
	}
	delete(d.persistPatchSet, path)
	d.persistPatchUnset = append(d.persistPatchUnset, path)
}

func (d *HeroDao) recordPersistPatchFull(field string) {
	if field == "" {
		return
	}
	if d.persistPatchFull == nil {
		d.persistPatchFull = make(map[string]bool)
	}
	d.persistPatchFull[field] = true
}

func (d *HeroDao) hasPersistPathPatch(field string) bool {
	return checkpoint.PersistPatchHasPath(d.persistPatchSet, d.persistPatchUnset, field)
}

func (d *HeroDao) appendPersistPathPatch(patch *checkpoint.PersistPatch, fullFields map[string]bool) {
	for path, value := range d.persistPatchSet {
		if checkpoint.PersistPatchPathCovered(path, fullFields) {
			continue
		}
		patch.Set[path] = value
	}
	for _, path := range d.persistPatchUnset {
		if checkpoint.PersistPatchPathCovered(path, fullFields) {
			continue
		}
		patch.Unset = append(patch.Unset, path)
	}
	d.clearPersistPathPatch()
}

func (d *HeroDao) clearPersistPathPatch() {
	d.persistPatchSet = nil
	d.persistPatchUnset = nil
	d.persistPatchFull = nil
}

func (d *HeroDao) markItemsKeyDirty(key int64, val int32) {
	if path, ok := checkpoint.MapPatchPath("items", key); ok {
		d.recordPersistPatchSet("items", path, val)
	} else {
		d.recordPersistPatchFull("items")
	}
	d.markItemsDirty()
}

func (d *HeroDao) markItemsKeyDeleted(key int64) {
	if path, ok := checkpoint.MapPatchPath("items", key); ok {
		d.recordPersistPatchUnset("items", path)
	} else {
		d.recordPersistPatchFull("items")
	}
	d.markItemsDirty()
}

func (d *HeroDao) markEquipsKeyDirty(key int64, val *EquipInfo) {
	if path, ok := checkpoint.MapPatchPath("equips", key); ok {
		d.recordPersistPatchSet("equips", path, val)
	} else {
		d.recordPersistPatchFull("equips")
	}
	d.markEquipsDirty()
}

func (d *HeroDao) markEquipsKeyDeleted(key int64) {
	if path, ok := checkpoint.MapPatchPath("equips", key); ok {
		d.recordPersistPatchUnset("equips", path)
	} else {
		d.recordPersistPatchFull("equips")
	}
	d.markEquipsDirty()
}

// Init wires dirty callbacks for nested structs and map values.
func (d *HeroDao) Init() {
	d.Pos.SetNotify(d.markPosDirty)
	if d.Equips != nil {
		d.Equips.Range(func(key int64, v *EquipInfo) bool {
			if v != nil {
				key, v := key, v
				v.SetNotify(func() { d.markEquipsKeyDirty(key, v) })
			}
			return true
		})
	}
}

// --- Setters ---

func (d *HeroDao) SetName(v string) {
	if d.Name != v {
		d.Name = v
		d.markNameDirty()
	}
}

func (d *HeroDao) SetLevel(v int32) {
	if d.Level != v {
		d.Level = v
		d.markLevelDirty()
	}
}

func (d *HeroDao) SetExp(v int64) {
	if d.Exp != v {
		d.Exp = v
		d.markExpDirty()
	}
}

func (d *HeroDao) SetLoginAt(v int64) {
	if d.LoginAt != v {
		d.LoginAt = v
		d.markLoginAtDirty()
	}
}

func (d *HeroDao) GetItems(key int64) (int32, bool) {
	if d.Items == nil {
		var zero int32
		return zero, false
	}
	return d.Items.Get(key)
}

func (d *HeroDao) SetItems(key int64, val int32) {
	if d.Items == nil {
		d.Items = fmap.NewSmallSafeMap[int64, int32](0)
	}
	d.Items.Set(key, val)
	d.markItemsKeyDirty(key, val)
}

func (d *HeroDao) DelItems(key int64) {
	if d.Items == nil {
		return
	}
	if d.Items.Delete(key) {
		d.markItemsKeyDeleted(key)
	}
}

func (d *HeroDao) RangeItems(f func(key int64, val int32) bool) {
	if d.Items == nil || f == nil {
		return
	}
	d.Items.Range(f)
}

func (d *HeroDao) ItemsLen() int {
	if d.Items == nil {
		return 0
	}
	return d.Items.Len()
}

func (d *HeroDao) AddFriends(v int64) {
	d.Friends = append(d.Friends, v)
	d.markFriendsDirty()
}

func (d *HeroDao) SetFriendsAll(v []int64) {
	d.Friends = v
	d.markFriendsDirty()
}

func (d *HeroDao) RangeFriends(f func(idx int, val int64) bool) {
	for i, v := range d.Friends {
		if !f(i, v) {
			break
		}
	}
}

func (d *HeroDao) FriendsLen() int {
	return len(d.Friends)
}

func (d *HeroDao) SetPos(v Position) {
	d.Pos = v
	d.Pos.SetNotify(d.markPosDirty)
	d.markPosDirty()
}

func (d *HeroDao) GetEquips(key int64) (*EquipInfo, bool) {
	if d.Equips == nil {
		var zero *EquipInfo
		return zero, false
	}
	return d.Equips.Get(key)
}

func (d *HeroDao) SetEquips(key int64, val *EquipInfo) {
	if d.Equips == nil {
		d.Equips = fmap.NewSmallSafeMap[int64, *EquipInfo](0)
	}
	if val != nil {
		val.SetNotify(func() { d.markEquipsKeyDirty(key, val) })
	}
	d.Equips.Set(key, val)
	d.markEquipsKeyDirty(key, val)
}

func (d *HeroDao) DelEquips(key int64) {
	if d.Equips == nil {
		return
	}
	if v, ok := d.Equips.Get(key); ok && v != nil {
		v.SetNotify(nil)
	}
	if d.Equips.Delete(key) {
		d.markEquipsKeyDeleted(key)
	}
}

func (d *HeroDao) RangeEquips(f func(key int64, val *EquipInfo) bool) {
	if d.Equips == nil || f == nil {
		return
	}
	d.Equips.Range(f)
}

func (d *HeroDao) EquipsLen() int {
	if d.Equips == nil {
		return 0
	}
	return d.Equips.Len()
}

func (d *HeroDao) heroDaoItemsRawMap() map[int64]int32 {
	if d.Items == nil {
		return nil
	}
	ret := make(map[int64]int32, d.Items.Len())
	d.Items.Range(func(key int64, val int32) bool {
		ret[key] = val
		return true
	})
	return ret
}

func (d *HeroDao) setItemsRawMap(src map[int64]int32) {
	d.Items = fmap.NewSmallSafeMap[int64, int32](len(src))
	for key, val := range src {
		d.Items.Set(key, val)
	}
}

func (d *HeroDao) heroDaoEquipsRawMap() map[int64]*EquipInfo {
	if d.Equips == nil {
		return nil
	}
	ret := make(map[int64]*EquipInfo, d.Equips.Len())
	d.Equips.Range(func(key int64, val *EquipInfo) bool {
		ret[key] = val
		return true
	})
	return ret
}

func (d *HeroDao) setEquipsRawMap(src map[int64]*EquipInfo) {
	d.Equips = fmap.NewSmallSafeMap[int64, *EquipInfo](len(src))
	for key, val := range src {
		if val != nil {
			key, val := key, val
			val.SetNotify(func() { d.markEquipsKeyDirty(key, val) })
		}
		d.Equips.Set(key, val)
	}
}

// --- Marshal (persist fields) ---

func (d *HeroDao) Marshal() []byte {
	return d.MarshalPersist(checkpoint.DirtyAll)
}

func (d *HeroDao) MarshalPersist(mask uint64) []byte {
	data := d.marshalPersistData(mask)
	if mask == checkpoint.DirtyAll {
		d.clearPersistPathPatch()
	}
	return data
}

func (d *HeroDao) marshalPersistData(mask uint64) []byte {
	_ = mask // full payload is used for inserts and safe fallback.
	doc := bson.M{
		"_id":      d.id,
		"_schema":  HeroDaoSchemaVersion,
		"name":     d.Name,
		"level":    d.Level,
		"exp":      d.Exp,
		"login_at": d.LoginAt,
		"items":    d.heroDaoItemsRawMap(),
		"friends":  d.Friends,
		"pos":      d.Pos,
		"equips":   d.heroDaoEquipsRawMap(),
	}
	data, _ := bson.Marshal(doc)
	return data
}

func (d *HeroDao) MarshalPersistPatch(mask uint64) checkpoint.PersistPatch {
	patch := checkpoint.PersistPatch{
		Set:      make(map[string]any),
		FullData: d.marshalPersistData(checkpoint.DirtyAll),
	}
	if mask == 0 || mask == checkpoint.DirtyAll {
		d.clearPersistPathPatch()
		return patch
	}
	fullFields := make(map[string]bool)
	if mask&heroDaoFieldName != 0 {
		patch.Set["name"] = d.Name
	}
	if mask&heroDaoFieldLevel != 0 {
		patch.Set["level"] = d.Level
	}
	if mask&heroDaoFieldExp != 0 {
		patch.Set["exp"] = d.Exp
	}
	if mask&heroDaoFieldLoginAt != 0 {
		patch.Set["login_at"] = d.LoginAt
	}
	if mask&heroDaoFieldItems != 0 {
		if d.persistPatchFull["items"] || !d.hasPersistPathPatch("items") {
			patch.Set["items"] = d.heroDaoItemsRawMap()
			fullFields["items"] = true
		}
	}
	if mask&heroDaoFieldFriends != 0 {
		patch.Set["friends"] = d.Friends
	}
	if mask&heroDaoFieldPos != 0 {
		patch.Set["pos"] = d.Pos
	}
	if mask&heroDaoFieldEquips != 0 {
		if d.persistPatchFull["equips"] || !d.hasPersistPathPatch("equips") {
			patch.Set["equips"] = d.heroDaoEquipsRawMap()
			fullFields["equips"] = true
		}
	}
	d.appendPersistPathPatch(&patch, fullFields)
	if len(patch.Set) == 0 {
		patch.Set = nil
	}
	return patch
}

func (d *HeroDao) MarshalSync(mask uint64) []byte {
	doc := bson.M{
		"_id": d.id,
	}
	if mask&heroDaoFieldName != 0 {
		doc["name"] = d.Name
	}
	if mask&heroDaoFieldLevel != 0 {
		doc["level"] = d.Level
	}
	if mask&heroDaoFieldExp != 0 {
		doc["exp"] = d.Exp
	}
	if mask&heroDaoFieldItems != 0 {
		doc["items"] = d.heroDaoItemsRawMap()
	}
	if mask&heroDaoFieldFriends != 0 {
		doc["friends"] = d.Friends
	}
	if mask&heroDaoFieldPos != 0 {
		doc["pos"] = d.Pos
	}
	if mask&heroDaoFieldEquips != 0 {
		doc["equips"] = d.heroDaoEquipsRawMap()
	}
	if len(doc) == 1 {
		return nil
	}
	data, _ := bson.Marshal(doc)
	return data
}

func (d *HeroDao) ApplySync(raw []byte) error {
	var doc bson.M
	if err := bson.Unmarshal(raw, &doc); err != nil {
		return err
	}
	if v, ok := doc["name"]; ok {
		data, err := bson.Marshal(bson.M{"v": v})
		if err != nil {
			return err
		}
		var wrap struct {
			V string `bson:"v"`
		}
		if err := bson.Unmarshal(data, &wrap); err != nil {
			return err
		}
		d.Name = wrap.V
	}
	if v, ok := doc["level"]; ok {
		data, err := bson.Marshal(bson.M{"v": v})
		if err != nil {
			return err
		}
		var wrap struct {
			V int32 `bson:"v"`
		}
		if err := bson.Unmarshal(data, &wrap); err != nil {
			return err
		}
		d.Level = wrap.V
	}
	if v, ok := doc["exp"]; ok {
		data, err := bson.Marshal(bson.M{"v": v})
		if err != nil {
			return err
		}
		var wrap struct {
			V int64 `bson:"v"`
		}
		if err := bson.Unmarshal(data, &wrap); err != nil {
			return err
		}
		d.Exp = wrap.V
	}
	if v, ok := doc["items"]; ok {
		data, err := bson.Marshal(bson.M{"v": v})
		if err != nil {
			return err
		}
		var wrap struct {
			V map[int64]int32 `bson:"v"`
		}
		if err := bson.Unmarshal(data, &wrap); err != nil {
			return err
		}
		d.setItemsRawMap(wrap.V)
	}
	if v, ok := doc["friends"]; ok {
		data, err := bson.Marshal(bson.M{"v": v})
		if err != nil {
			return err
		}
		var wrap struct {
			V []int64 `bson:"v"`
		}
		if err := bson.Unmarshal(data, &wrap); err != nil {
			return err
		}
		d.Friends = wrap.V
	}
	if v, ok := doc["pos"]; ok {
		data, err := bson.Marshal(bson.M{"v": v})
		if err != nil {
			return err
		}
		var wrap struct {
			V Position `bson:"v"`
		}
		if err := bson.Unmarshal(data, &wrap); err != nil {
			return err
		}
		d.Pos = wrap.V
	}
	if v, ok := doc["equips"]; ok {
		data, err := bson.Marshal(bson.M{"v": v})
		if err != nil {
			return err
		}
		var wrap struct {
			V map[int64]*EquipInfo `bson:"v"`
		}
		if err := bson.Unmarshal(data, &wrap); err != nil {
			return err
		}
		d.setEquipsRawMap(wrap.V)
	}
	d.Init()
	return nil
}

// --- Unmarshal ---

func (d *HeroDao) Unmarshal(raw []byte) error {
	type rawDoc struct {
		Id      int64                `bson:"_id"`
		Name    string               `bson:"name"`
		Level   int32                `bson:"level"`
		Exp     int64                `bson:"exp"`
		LoginAt int64                `bson:"login_at"`
		Items   map[int64]int32      `bson:"items"`
		Friends []int64              `bson:"friends"`
		Pos     Position             `bson:"pos"`
		Equips  map[int64]*EquipInfo `bson:"equips"`
	}
	var dd rawDoc
	if err := bson.Unmarshal(raw, &dd); err != nil {
		return err
	}
	d.id = dd.Id
	d.Name = dd.Name
	d.Level = dd.Level
	d.Exp = dd.Exp
	d.LoginAt = dd.LoginAt
	d.setItemsRawMap(dd.Items)
	d.Friends = dd.Friends
	d.Pos = dd.Pos
	d.setEquipsRawMap(dd.Equips)
	d.Init()
	return nil
}

// compile-time import guards
var (
	_ = checkpoint.DirtyTracker{}
	_ = bson.M{}
)
