// Code generated by tool/dao. DO NOT EDIT.
package testdata

import (
	"github.com/tjbdwanghaibo/cube-core/checkpoint"
)

// Position is a nested struct with dirty propagation.
type Position struct {
	checkpoint.DirtyHook
	X int32
	Y int32
}

func (s *Position) SetX(v int32) {
	if s.X != v {
		s.X = v
		s.Mark()
	}
}

func (s *Position) SetY(v int32) {
	if s.Y != v {
		s.Y = v
		s.Mark()
	}
}
